name: Create React App Typescript Tests
on:
  pull_request:
    paths:
      - 'examples/create-react-app-typescript/**'

jobs:
  playwright-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/playwright
        with:
          project: "replay-firefox"
          issue-number: ${{ github.event.pull_request.number }}
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
          working-directory: examples/create-react-app-typescript
